stages:
  - mirror

github_mirror:
  stage: mirror
  tags:
    - github_namboy94_push
  script:
    - git checkout master
    - git pull
    - git push git@github.com:namboy94/hikvision-client.git master -f
    - git checkout develop
    - git pull
    - git push git@github.com:namboy94/hikvision-client.git develop -f
