stages:
  - setup
  - test
  - upload
  - upgrade
  - cleanup

clone_master:
  stage: setup
  only:
    - master
  script:
    - cd
    - git clone git@gitlab.namibsun.net:namboy94/hikvision-client.git
    - git clone git@gitlab.namibsun.net:namboy94/hikvision-client.wiki.git
    - cd hikvision-client
    - git push -u git@gitlab.com:namboy94/hikvision-client.git --all
    - git push -u git@github.com:namboy94/hikvision-client.git --all
    - git push -u git@bitbucket.org:namboy94/hikvision-client.git --all

generate_statistics:
  stage: test
  only:
    - master
  script:
    - cd
    - cd hikvision-client
    - git_stats generate
    - cd
    - cd hikvision-client.wiki
    - cp -r ../hikvision-client/git_stats .

upload_to_pypi:
  stage: upload
  only:
    - master
  script:
    - cd
    - cd hikvision-client
    - python setup.py register sdist upload
  allow_failure: true

upload_documentation_and_statistics:
  stage: upload
  only:
    - master
  script:
    - cd
    - cd hikvision-client.wiki
    - git add --all
    - git commit -m "Updated statistics"
    - git push -u origin master

delete_clone_master:
  stage: cleanup
  when: always
  only:
    - master
  script:
    - cd
    - rm -rf hikvision-client
    - rm -rf hikvision-client.wiki

